# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "My two cents on Android"

# URL
baseurl:            "/blog"
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           rdiscount

# Navigation
nav:
  - name:           "Me"
    href:           "//dojester13.github.io"
  - name:           "Twitter"
    href:           "https://twitter.com/doJester13"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
